FROM golang:alpine AS build-dlv

RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM alpine:3.19.3 as certs
RUN apk --update add ca-certificates bash
ARG TARGETARCH
COPY bin/linux/deep-${TARGETARCH} /deep

COPY --from=build-dlv /go/bin/dlv /dlv
COPY /cmd/deep/entrypoint-debug.sh /entrypoint-debug.sh
EXPOSE 2345
ENTRYPOINT [ "/entrypoint-debug.sh" ]
CMD []
