version: "3"
services:

  distributor:
    image: intergral/deep:latest
    command: "-target=distributor -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep
      - "43315" # deep grpc ingest

  ingester-0:
    image: intergral/deep:latest
    command: "-target=ingester -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  ingester-1:
    image: intergral/deep:latest
    command: "-target=ingester -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  ingester-2:
    image: intergral/deep:latest
    command: "-target=ingester -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  query-frontend:
    image: intergral/deep:latest
    command: "-target=query-frontend -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300:3300"   # deep

  querier:
    image: intergral/deep:latest
    command: "-target=querier -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  compactor:
    image: intergral/deep:latest
    command: "-target=compactor -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  metrics-generator:
    image: intergral/deep:latest
    command: "-target=metrics-generator -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300"   # deep

  tracepoint:
    image: intergral/deep:latest
    command: "-target=tracepoint -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    depends_on:
      - minio
    ports:
      - "3300" #deep

  tracepoint-api:
    image: intergral/deep:latest
    command: "-target=tracepoint-api -config.file=/etc/deep.yaml"
    restart: always
    volumes:
      - ./deep-distributed.yaml:/etc/deep.yaml
    ports:
      - "3300" #deep
    depends_on:
      - minio


  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=deep
      - MINIO_SECRET_KEY=supersecret
    ports:
      - "9001:9001"
    entrypoint:
      - sh
      - -euc
      - mkdir -p /data/deep && minio server /data --console-address ':9001'

  test_app:
    image: intergral/deep-python:latest
    environment:
      - DEEP_SERVICE_URL=distributor:43315
      - DEEP_SERVICE_SECURE=False
    depends_on:
      - distributor

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../shared/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=https://github.com/intergral/plugin-signer/releases/download/intergral%2Fgrafana-deep-tracepoint-panel.v1.0.0/intergral-deep-tracepoint-panel-1.0.0.zip;intergral-deep-tracepoint-panel,https://github.com/intergral/plugin-signer/releases/download/intergral%2Fgrafana-deep-panel.v1.0.2/intergral-deep-panel-1.0.2.zip;intergral-deep-panel,https://github.com/intergral/plugin-signer/releases/download/intergral%2Fgrafana-deep-datasource.v1.0.3/intergral-deep-datasource-1.0.3.zip;intergral-deep-datasource
    ports:
      - "3000:3000"

  test_load:
    image: intergral/deep-cli
    depends_on:
      - distributor
    command:
      - generate
      - snapshot
      - --endpoint=distributor:43315
      - --count=3
      - --sleep=5
      - --iterations=-1
      - --random-string
      - --random-duration
      - --duration-nanos=1000000000
