{
 "title": "Deep / Tenants",
 "tags": [ "deep" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(deep_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(deep_build_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "tenant",
    "label": "tenant",
    "query": {
     "query": "label_values(deepdb_blocklist_length{cluster=\"$cluster\", job=~\"($namespace)/compactor\"},tenant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tenant info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Limits",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (deep_limits_overrides{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",user=\"$tenant\"})\n  or max by (cluster, namespace, limit_name) (deep_limits_defaults{cluster=~\"$cluster\", job=~\"($namespace)/compactor\"})\n) by (limit_name)\n"
    }
   ]
  },
  {
   "title": "Ingestion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Distributor bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(deep_distributor_bytes_received_total{cluster=~\"$cluster\", job=~\"($namespace)/distributor\",tenant=\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (deep_limits_overrides{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",user=\"$tenant\",limit_name=\"ingestion_rate_limit_bytes\"})\n  or max by (cluster, namespace, limit_name) (deep_limits_defaults{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",limit_name=\"ingestion_rate_limit_bytes\"})\n) by (ingestion_rate_limit_bytes)\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (deep_limits_overrides{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",user=\"$tenant\",limit_name=\"ingestion_burst_size_bytes\"})\n  or max by (cluster, namespace, limit_name) (deep_limits_defaults{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",limit_name=\"ingestion_burst_size_bytes\"})\n) by (ingestion_burst_size_bytes)\n",
     "legendFormat": "burst limit"
    }
   ]
  },
  {
   "title": "Distributor spans/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(deep_distributor_spans_received_total{cluster=~\"$cluster\", job=~\"($namespace)/distributor\",tenant=\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(deep_discarded_spans_total{cluster=~\"$cluster\", job=~\"($namespace)/distributor\",tenant=\"$tenant\"}[$__rate_interval])) by (reason)",
     "legendFormat": "refused {{ reason }}"
    }
   ]
  },
  {
   "title": "Live traces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(deep_ingester_live_snapshots{cluster=~\"$cluster\", job=~\"($namespace)/ingester\",tenant=\"$tenant\"})",
     "legendFormat": "live traces"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (deep_limits_overrides{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",user=\"$tenant\",limit_name=\"max_global_traces_per_user\"})\n  or max by (cluster, namespace, limit_name) (deep_limits_defaults{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",limit_name=\"max_global_traces_per_user\"})\n) by (max_global_traces_per_user)\n",
     "legendFormat": "global limit"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (deep_limits_overrides{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",user=\"$tenant\",limit_name=\"max_local_traces_per_user\"})\n  or max by (cluster, namespace, limit_name) (deep_limits_defaults{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",limit_name=\"max_local_traces_per_user\"})\n) by (max_local_traces_per_user)\n",
     "legendFormat": "local limit"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queries/s (ID lookup)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(deep_query_frontend_queries_total{cluster=~\"$cluster\", job=~\"($namespace)/query-frontend\",tenant=\"$tenant\",op=\"snapshots\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Queries/s (search)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(deep_query_frontend_queries_total{cluster=~\"$cluster\", job=~\"($namespace)/query-frontend\",tenant=\"$tenant\",op=\"search\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blockslist length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(deepdb_blocklist_length{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",tenant=\"$tenant\"})",
     "legendFormat": "length"
    }
   ]
  },
  {
   "title": "Outstanding compactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(deepdb_compaction_outstanding_blocks{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",tenant=\"$tenant\"})\n/\ncount(deep_build_info{cluster=~\"$cluster\", job=~\"($namespace)/compactor\"})\n",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Metrics generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(deep_metrics_generator_bytes_received_total{cluster=~\"$cluster\", job=~\"($namespace)/metrics-generator\",tenant=\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Active series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(deep_metrics_generator_registry_active_series{cluster=~\"$cluster\", job=~\"($namespace)/metrics-generator\",tenant=\"$tenant\"})",
     "legendFormat": "{{ tenant }}"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (deep_limits_overrides{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",user=\"$tenant\",limit_name=\"metrics_generator_max_active_series\"})\n  or max by (cluster, namespace, limit_name) (deep_limits_defaults{cluster=~\"$cluster\", job=~\"($namespace)/compactor\",limit_name=\"metrics_generator_max_active_series\"})\n) by (metrics_generator_max_active_series)\n",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}