{
 "title": "Deep Operational",
 "tags": [ "deep" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(deep_build_info, instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(deep_build_info{instance=~'$cluster'}, namespace)"
    }
   },
   {
    "name": "component",
    "query": "compactor,distributor,ingester,metrics-generator,query-frontend,querier,cortex-gw,cortex-gw-internal"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gcs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "go heap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$cluster\", job=\"deep\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$cluster\", job=\"deep\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "working set",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{instance=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "tx/rx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{instance=\"$cluster\", pod=~\"$component.*\"}[$__rate_interval])",
     "legendFormat": "rx-{{pod}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{instance=\"$cluster\", pod=~\"$component.*\"}[$__rate_interval])",
     "legendFormat": "tx-{{pod}}"
    }
   ]
  },
  {
   "title": "data volume free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{instance=\"$cluster\", persistentvolumeclaim=~\"$component.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "bad words",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(promtail_custom_bad_words_total{instance=\"$cluster\", exported_app=~\"$component.*\"}[$__rate_interval])",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "%age total work queue",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "deepdb_work_queue_length{instance=\"$cluster\", job=\"deep\"} / deepdb_work_queue_max{instance=\"$cluster\", job=\"deep\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "maintenance errors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(deepdb_compaction_errors_total{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (job)",
       "legendFormat": "compaction_err"
      },
      {
       "expr": "sum(increase(deepdb_retention_errors_total{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (job)",
       "legendFormat": "retention_err"
      },
      {
       "expr": "sum(increase(deepdb_blocklist_poll_errors_total{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (job)",
       "legendFormat": "blocklist_err"
      }
     ]
    },
    {
     "title": "Blocklist Poll Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deepdb_blocklist_poll_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deepdb_blocklist_poll_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deepdb_blocklist_poll_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Blocklist Length",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(deepdb_blocklist_length{instance=\"$cluster\", job=\"deep\"}) by (tenant)",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "retention duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deepdb_retention_duration_seconds_bucket{instance=\"$cluster\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deepdb_retention_duration_seconds_bucket{instance=\"$cluster\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deepdb_retention_duration_seconds_bucket{instance=\"$cluster\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "retention",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(deepdb_retention_deleted_total{instance=\"$cluster\", job=\"deep\"}[$__rate_interval]))",
       "legendFormat": "deleted"
      },
      {
       "expr": "sum(increase(deepdb_retention_marked_for_deletion_total{instance=\"$cluster\", job=\"deep\"}[$__rate_interval]))",
       "legendFormat": "marked_for_deletion"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{instance=\"$cluster\", namespace=\"$namespace\"}[5m]) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries/Sec (cortex-gw)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deep_request_duration_seconds_count{route=~\".*api_traces_traceid\", instance=\"$cluster\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Query Latency (Gateway)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Search Queries/Sec (cortex-gw)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deep_request_duration_seconds_count{route=~\".*api_search.*\", instance=\"$cluster\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Search Query Latency (Gateway)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Queries/Sec (Query Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deep_request_duration_seconds_count{instance=\"$cluster\", route=~\".*api_traces_traceid\", job=\"deep\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Query Latency (Query Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Search Queries/Sec (Query Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deep_request_duration_seconds_count{instance=\"$cluster\", route=~\".*api_search.*\", job=\"deep\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Search Query Latency (Query Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Queries/Sec (Querier)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deep_request_duration_seconds_count{route=~\"querier_.*api_traces_traceid\", instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Query Latency (Querier)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Search Queries/Sec (Querier)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deep_request_duration_seconds_count{route=~\"querier_.*api_search.*\", instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Search Query Latency (Querier)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Queries/Sec (Ingester)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deep_request_duration_seconds_count{route=\"/deeppb.Querier/FindTraceByID\", instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Query Latency (Ingester)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 4, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=\"/deeppb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=\"/deeppb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=\"/deeppb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Search Queries/Sec (Ingester)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deep_request_duration_seconds_count{route=~\"/deeppb.Querier/Search.*\", instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Search Query Latency (Ingester)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"/deeppb.Querier/Search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"/deeppb.Querier/Search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"/deeppb.Querier/Search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5",
       "stepMode": "min"
      }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshots Received",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(cluster) (rate(deep_distributor_snapshots_received_total{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Snapshots Created",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(cluster) (rate(deep_ingester_snapshots_created_total{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Blocks Flushed (1h)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(deep_ingester_blocks_flushed_total{instance=\"$cluster\", job=\"deep\"}[1h]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Failed Flushes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(deep_ingester_failed_flushes_total{instance=\"$cluster\", namespace=\"$namespace\"}[5m]) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Blocks Cleared (1h)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(deep_ingester_blocks_cleared_total{instance=\"$cluster\", namespace=\"$namespace\"}[1h]))"
      }
     ]
    },
    {
     "title": "Flush Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_ingester_flush_duration_seconds_bucket{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_ingester_flush_duration_seconds_bucket{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_ingester_flush_duration_seconds_bucket{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Pushes/sec (gateway)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deep_request_duration_seconds_count{instance=\"$cluster\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "OTEL Distributor Snapshots/second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 7, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(deep_receiver_accepted_snapshots{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "accepted"
      },
      {
       "expr": "sum(rate(deep_receiver_refused_snapshots{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "refused"
      }
     ]
    },
    {
     "title": "Push Latency (Gateway)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 13, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Push Latency (Ingester)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 13, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"/deeppb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"/deeppb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deep_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\", route=~\"/deeppb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cortex_memcache_request_duration_seconds_count{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (status_code, method)",
       "legendFormat": "{{status_code}}-{{method}}"
      }
     ]
    },
    {
     "title": "Latency By Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_memcache_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (method, le))",
       "legendFormat": ".99-{{method}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_memcache_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (method, le))",
       "legendFormat": ".9-{{method}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_memcache_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (method, le))",
       "legendFormat": ".5-{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deepdb_backend_request_duration_seconds_count{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Latency By Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deepdb_backend_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(deepdb_backend_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(deepdb_backend_request_duration_seconds_bucket{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ring/Memberlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossip Health",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "gauge_memberlist_health_score{instance=\"$cluster\", job=\"deep\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Health",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deep_memberlist_client_cluster_node_health_score{instance=\"$cluster\", job=\"deep\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Member Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(deep_memberlist_client_cluster_members_count{instance=\"$cluster\", job=\"deep\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(deep_memberlist_client_cluster_members_count{instance=\"$cluster\", job=\"deep\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "KV Store Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(deep_memberlist_client_kv_store_count{instance=\"$cluster\", job=\"deep\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(deep_memberlist_client_kv_store_count{instance=\"$cluster\", job=\"deep\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Vulture",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vulture Query Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(deep_vulture_trace_error_total{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (error) / ignoring (error) group_left sum(rate(deep_vulture_trace_total{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{error}}"
      }
     ]
    },
    {
     "title": "Average Vulture Query Errors",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(deep_vulture_trace_error_total{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (error) / ignoring (error) group_left sum(rate(deep_vulture_trace_total{instance=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{secondsago}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compactor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects Combined / s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deepdb_compaction_objects_combined_total{instance=\"$cluster\"}[$__rate_interval])) by (level)"
      }
     ]
    },
    {
     "title": "Objects Written / s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deepdb_compaction_objects_written_total{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (level)"
      }
     ]
    },
    {
     "title": "Bytes Written / s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(deepdb_compaction_bytes_written_total{instance=\"$cluster\", job=\"deep\"}[$__rate_interval])) by (level)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocks Compacted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(deepdb_compaction_blocks_total{instance=\"$cluster\", job=\"deep\"}[5m])) by (level)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}