{
 "title": "Deep / Resources",
 "tags": [ "deep" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(deep_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(deep_build_info{cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{namespace=~\"$namespace\"} / container_spec_cpu_period{namespace=~\"$namespace\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{namespace=~\"$namespace\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod, container) (go_memstats_heap_inuse_bytes{ job=~\"($namespace)/.*\"})",
     "legendFormat": "{{container}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{ namespace=~\"$namespace\",container=~\"distributor\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{ namespace=~\"$namespace\",container=~\"distributor\"} / container_spec_cpu_period{ namespace=~\"$namespace\",container=~\"distributor\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\",container=~\"distributor\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=~\"$namespace\",container=~\"distributor\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{namespace=~\"$namespace\",container=~\"distributor\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"distributor\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{job=~\"($namespace)/distributor\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{ namespace=~\"$namespace\",container=~\"ingester\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{ namespace=~\"$namespace\",container=~\"ingester\"} / container_spec_cpu_period{ namespace=~\"$namespace\",container=~\"ingester\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"ingester\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{ namespace=~\"$namespace\",container=~\"ingester\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{ namespace=~\"$namespace\",container=~\"ingester\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"ingester\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{ job=~\"($namespace)/ingester\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Metrics-generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{ namespace=~\"$namespace\",container=~\"metrics-generator\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{ namespace=~\"$namespace\",container=~\"metrics-generator\"} / container_spec_cpu_period{ namespace=~\"$namespace\",container=~\"metrics-generator\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"metrics-generator\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{ namespace=~\"$namespace\",container=~\"metrics-generator\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{ namespace=~\"$namespace\",container=~\"metrics-generator\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"metrics-generator\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{ job=~\"($namespace)/metrics-generator\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Query Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{ namespace=~\"$namespace\",container=~\"query-frontend\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{ namespace=~\"$namespace\",container=~\"query-frontend\"} / container_spec_cpu_period{ namespace=~\"$namespace\",container=~\"query-frontend\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"query-frontend\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{ namespace=~\"$namespace\",container=~\"query-frontend\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{ namespace=~\"$namespace\",container=~\"query-frontend\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"query-frontend\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{ job=~\"($namespace)/query-frontend\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Querier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{ namespace=~\"$namespace\",container=~\"querier\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{ namespace=~\"$namespace\",container=~\"querier\"} / container_spec_cpu_period{ namespace=~\"$namespace\",container=~\"querier\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"querier\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{ namespace=~\"$namespace\",container=~\"querier\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{ namespace=~\"$namespace\",container=~\"querier\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"querier\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{ job=~\"($namespace)/querier\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Compactor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{ namespace=~\"$namespace\",container=~\"compactor\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{ namespace=~\"$namespace\",container=~\"compactor\"} / container_spec_cpu_period{ namespace=~\"$namespace\",container=~\"compactor\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"compactor\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{ namespace=~\"$namespace\",container=~\"compactor\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{ namespace=~\"$namespace\",container=~\"compactor\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{ namespace=~\"$namespace\",container=~\"compactor\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{ job=~\"($namespace)/compactor\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}