version: "3"
services:

  deep:
    image: intergral/deep-debug:latest
    command: [ "-config.file=/etc/deep.yaml" ]
    volumes:
      - ../shared/deep.yaml:/etc/deep.yaml
      - ./deep-data:/tmp/deep
    environment:
      - DEBUG_BLOCK=0
    ports:
      - "3300:3300"   # deep http
      - "43315:43315"   # deep grpc
      - "2345:2345"   # delve debug server

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ../shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ../shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../shared/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=https://github.com/intergral/plugin-signer/releases/download/intergral%2Fgrafana-deep-tracepoint-panel.v1.0.0/intergral-deep-tracepoint-panel-1.0.0.zip;intergral-deep-tracepoint-panel,https://github.com/intergral/plugin-signer/releases/download/intergral%2Fgrafana-deep-panel.v1.0.2/intergral-deep-panel-1.0.2.zip;intergral-deep-panel,https://github.com/intergral/plugin-signer/releases/download/intergral%2Fgrafana-deep-datasource.v1.0.3/intergral-deep-datasource-1.0.3.zip;intergral-deep-datasource
    ports:
      - "3000:3000"

  test_app:
    image: intergral/deep-python:master
    environment:
      - DEEP_SERVICE_SECURE=False
    depends_on:
      - deep

  test_load:
    image: intergral/deep-cli
    command:
      - generate
      - snapshot
      - --endpoint=deep:43315
      - --count=3
      - --sleep=5
      - --iterations=-1
      - --random-string
      - --random-duration
      - --duration-nanos=1000000000
